### ISSUE TITLE
how to connect to a nats server with username and password

### ISSUE THREAD

**Issue by shangshujie** [tyagihas/java_nats#1]
my compony's nats server need authorized, witch means i need add username and pass to NATS when connected.
just like this:
nats://nats:nats@x.x.x.x:4222/

can this java-nats-client support this?

**Comment by derekcollison** [comment]
Looks like you could add in "user" and "pass" to the properties when making a connection.

https://github.com/tyagihas/java_nats/blob/master/lib/org/nats/Connection.java#L108

**Comment by tyagihas** [comment]
Yes, you can set "user" and "pass" to Properties object and pass it as a parameter to "connect(Properties popts)".

Or do you want to specify it as a single line?

**Comment by zhouxinyu** [comment]
I have set "user" and "pass" to Properties, and the examples can connect to the server(cloud foundry's nats) , but the sub examples can not receive the data from the pub examples . Anyone can help me?

**Comment by tyagihas** [comment]
This should be resolved with the latest build. Please reopen a ticket if you still see the issue.

**Comment by lenovouser** [comment]
@tyagihas could you provide one quick example on how to connect to e.g.

```
nats.mydomain.tld
nats-user
T0pS3cr3t
```

**Comment by tyagihas** [comment]
I've just added a quick example. Please confirm.

https://github.com/tyagihas/java_nats/blob/master/src/test/java/org/nats/examples/Auth.java
