### ISSUE TITLE
BufferUnderflowException when handling large messages

### ISSUE THREAD

**Issue by kosii** [tyagihas/java_nats#3]
I'm struggling with the same issue as the author of this mail:
https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/GPvXpyNCW7A/-DBpY_EFi24J
Basically we can't consume large messages fast enough without having a BufferUnderflowException:

```
Exception in thread "Thread-0" java.nio.BufferUnderflowException
    at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:265)
    at org.nats.Connection$MsgProcessor.processMessage(Connection.java:751)
    at org.nats.Connection$MsgProcessor.run(Connection.java:698)
```

My message handler looks like this (sorry for the Scala):

```
val suid = conn.subscribe("events",
  new MsgHandler {
    override def execute(msg: String) {
      println(s"Received update : $msg")
    }
  }
)
```

Any ideas?

**Comment by tyagihas** [comment]
Thank you for the feedback. I will take a look.
What is your message size and number of messages published?

**Comment by SharpMan** [comment]
I think you should allow auto expanding of the byte buffer btw
