### ISSUE TITLE
Catching Error/Exceptions

### ISSUE THREAD

**Issue by simao** [tyagihas/java_nats#9]
Hello,

I am trying to use this library (through it's scala api, but I think this problem is caused by the java api), and I am running into some problems when there are some exceptions, for example when the server goes down.

java_nats indeed tries to reconnect, but if the reconnection fails, it just logs the problem and never throws an exception, and never tries again either. This is a problem because the code calling this library cannot act on the error as it never receives an indication that there is an error, like an exception or an error callback.

Is this intended?

Thanks,
Simao

**Comment by tyagihas** [comment]
Hi,

I understand the issue. I will change it to throw an exception and let you know within a week.

Thanks.
Teppei

**Comment by simao** [comment]
Hi,

Thanks for looking into it. If you have an idea of how you would like to have this implemented I can also help.

Cheers,
Simao

**Comment by tyagihas** [comment]
Hi,

I've just pushed the latest code with following changes : 
- Throw an IOException to a caller thread when a connection is invalid.
- Connection.connect has a third parameter, disconnectHandler, which is invoked when reconnect process fails completely.

The binary file should be available within a few hours.

Thanks.
Teppei

**Comment by simao** [comment]
Hi,

Many thanks for the change. Are you planning to release a scala_nats version with the latest java nats as a dependency?

**Comment by tyagihas** [comment]
I just updated scala_nats code and uploaded binary files, which should be available through maven in next few hours. 

Please note that I made a minor change in java_nats 0.6.1 today so if you already download it yesterday, make sure to refresh it.

cheers,
Teppei

**Comment by simao** [comment]
Maybe this is an error in my build configuration, I am getting some unresolved dependency errors when downloading scala nats and it seems it's not available at `https://oss.sonatype.org/content/repositories/releases/com/github/tyagihas/scala_nats_2.11/` ? Do I need a different repo?

Thanks!

**Comment by tyagihas** [comment]
No. You are right. The repo wasn't released properly. 

"0.2.1" should be available in sonatype now. Can you try it again?

**Comment by tyagihas** [comment]
Hi,

I'm closing this issue for now. Please reopen it if you still any issue.

Thanks.
Teppei

**Comment by simao** [comment]
Hi,

Thanks for working on this!

Unfortunately I didn't have time yet to try it out because the handler is provided on the connection stage and not on the subscription, and this does not fit with our current design, I will have to find a way around this, which can take some time until I get to work on it again.

Cheers,
Simao

**Comment by tyagihas** [comment]
Hi,

I'm not sure how much this impacts on your design, but one approach is defining a disconnect handler with an external function call and later on (eg. subscription timing), dynamically overriding the function call to something else.

Regards,
Teppei

**Comment by simao** [comment]
Hi,

Yeah the problem was the connection was being setup before an akka streams materialization and the subscribing was done during materialization.

But anyway, I just changed this and everything works as expected.

Thank you very much for fixing!
